packages:
    - 'packages/*'
    - 'apps/*'

catalog:
    '@primeuix/styled': ^0.7.2
    '@primeuix/utils': ^0.6.1
    '@primeuix/styles': ^1.2.3
    '@primeuix/themes': ^1.2.3
    'tailwindcss-primeui': ^0.6.1
    'primeicons': ^7.0.0

catalogs:
    angular20:
        "@angular-devkit/build-angular": ^20.0.3
        "@angular/animations": ^20.0.4
        "@angular/cdk": ^20.0.3
        "@angular/cli": ^20.0.3
        "@angular/common": ^20.0.4
        "@angular/compiler": ^20.0.4
        "@angular/compiler-cli": ^20.0.4
        "@angular/core": ^20.0.4
        "@angular/forms": ^20.0.4
        "@angular/platform-browser": ^20.0.4
        "@angular/platform-browser-dynamic": ^20.0.4
        "@angular/platform-server": ^20.0.4
        "@angular/router": ^20.0.4
        "@angular/ssr": ^20.0.3
        "@angular-eslint/eslint-plugin": ^20.0.4
        "@angular-eslint/eslint-plugin-template": ^20.0.4
        "@angular-eslint/schematics": ^20.0.4
        "@angular-eslint/template-parser": ^20.0.4
        "zone.js": ~0.15.0
        "ng-packagr": 20.0.1
        "typescript": 5.8.3
