packages:
    - 'packages/*'
    - 'apps/*'

catalog:
    '@primeuix/styled': ^0.7.4
    '@primeuix/utils': ^0.6.3
    '@primeuix/styles': ^1.2.5
    '@primeuix/themes': ^1.2.5
    '@primeuix/motion': ^0.0.9
    'tailwindcss-primeui': ^0.6.1
    'primeicons': ^7.0.0

catalogs:
    angular21:
        "@angular-devkit/build-angular": ^21.0.0
        "@angular/cdk": ^21.0.0
        "@angular/cli": ^21.0.0
        "@angular/common": ^21.0.0
        "@angular/compiler": ^21.0.0
        "@angular/compiler-cli": ^21.0.0
        "@angular/core": ^21.0.0
        "@angular/forms": ^21.0.0
        "@angular/platform-browser": ^21.0.0
        "@angular/platform-browser-dynamic": ^21.0.0
        "@angular/platform-server": ^21.0.0
        "@angular/router": ^21.0.0
        "@angular/ssr": ^21.0.0
        "@angular-eslint/eslint-plugin": ^20.6.0
        "@angular-eslint/eslint-plugin-template": ^20.6.0
        "@angular-eslint/schematics": ^20.6.0
        "@angular-eslint/template-parser": ^20.6.0
        "ng-packagr": 21.0.0
        "typescript": 5.9.3
