/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i1 from './datatable';
export declare const DataTableModuleNgFactory: i0.NgModuleFactory<i1.DataTableModule>;
export declare const RenderType_DataTable: i0.RendererType2;
export declare function View_DataTable_0(_l: any): i0.ɵViewDefinition;
export declare function View_DataTable_Host_0(_l: any): i0.ɵViewDefinition;
export declare const DataTableNgFactory: i0.ComponentFactory<i1.DataTable>;
export declare const RenderType_DTRadioButton: i0.RendererType2;
export declare function View_DTRadioButton_0(_l: any): i0.ɵViewDefinition;
export declare function View_DTRadioButton_Host_0(_l: any): i0.ɵViewDefinition;
export declare const DTRadioButtonNgFactory: i0.ComponentFactory<i1.DTRadioButton>;
export declare const RenderType_DTCheckbox: i0.RendererType2;
export declare function View_DTCheckbox_0(_l: any): i0.ɵViewDefinition;
export declare function View_DTCheckbox_Host_0(_l: any): i0.ɵViewDefinition;
export declare const DTCheckboxNgFactory: i0.ComponentFactory<i1.DTCheckbox>;
export declare const RenderType_ColumnHeaders: i0.RendererType2;
export declare function View_ColumnHeaders_0(_l: any): i0.ɵViewDefinition;
export declare function View_ColumnHeaders_Host_0(_l: any): i0.ɵViewDefinition;
export declare const ColumnHeadersNgFactory: i0.ComponentFactory<i1.ColumnHeaders>;
export declare const RenderType_ColumnFooters: i0.RendererType2;
export declare function View_ColumnFooters_0(_l: any): i0.ɵViewDefinition;
export declare function View_ColumnFooters_Host_0(_l: any): i0.ɵViewDefinition;
export declare const ColumnFootersNgFactory: i0.ComponentFactory<i1.ColumnFooters>;
export declare const RenderType_TableBody: i0.RendererType2;
export declare function View_TableBody_0(_l: any): i0.ɵViewDefinition;
export declare function View_TableBody_Host_0(_l: any): i0.ɵViewDefinition;
export declare const TableBodyNgFactory: i0.ComponentFactory<i1.TableBody>;
export declare const RenderType_ScrollableView: i0.RendererType2;
export declare function View_ScrollableView_0(_l: any): i0.ɵViewDefinition;
export declare function View_ScrollableView_Host_0(_l: any): i0.ɵViewDefinition;
export declare const ScrollableViewNgFactory: i0.ComponentFactory<i1.ScrollableView>;
export declare const RenderType_RowExpansionLoader: i0.RendererType2;
export declare function View_RowExpansionLoader_0(_l: any): i0.ɵViewDefinition;
export declare function View_RowExpansionLoader_Host_0(_l: any): i0.ɵViewDefinition;
export declare const RowExpansionLoaderNgFactory: i0.ComponentFactory<i1.RowExpansionLoader>;
