export class DynamicDialogConfig {
	data?: any;
	header?: string;
	footer?: string;
	width?: string;
	height?: string;
	closeOnEscape?: boolean;
	baseZIndex?: number;
	autoZIndex?: boolean;
	dismissableMask?: boolean;
	rtl?: boolean;
	style?: any;
	contentStyle?: any;
	styleClass?: string;
	transitionOptions?: string;
	closable?: boolean;
	showHeader?: boolean;
	modal?: boolean;
	maskStyleClass?: string;
    resizable?: boolean;
    draggable?: boolean;
    keepInViewport?: boolean;
    minX?: number;
    minY?: number;
    maximizable?: boolean;
    maximizeIcon?: string;
    minimizeIcon?: string;
    position?: string;
    onMaximize?: (value?:any) => void;
    onShow?: (value?: any) => void;
    onClose?: (value?: any) => void;
    onResizeInit?: (event?: MouseEvent) => void;
    onResizeEnd?: (value?: any) => void;
    onDragEnd?: (event?: MouseEvent) => void;
    onDragStart?: (event?: MouseEvent) => void;
}
