export enum FilterMatchMode {
    STARTS_WITH = "startsWith",
    CONTAINS = "contains",
    NOT_CONTAINS = "notContains",
    ENDS_WITH = "endsWith",
    EQUALS = "equals",
    NOT_EQUALS = "notEquals",
    IN = "in",
    LESS_THAN = "lt",
    LESS_THAN_OR_EQUAL_TO = "lte",
    GREATER_THAN = "gt",
    GREATER_THAN_OR_EQUAL_TO = "gte",
    BETWEEN = "between",
    IS = "is",
    IS_NOT = "isNot",
    BEFORE = "before",
    AFTER = "after",
    DATE_IS = "dateIs",
    DATE_IS_NOT = "dateIsNot",
    DATE_BEFORE = "dateBefore",
    DATE_AFTER = "dateAfter",
}