import {Injectable} from 'angular2/core';
import {Http, Response} from 'angular2/http';
import {Car} from '../domain/car';

@Injectable()
export class CarService {
    
    constructor(private http: Http) {}

    getCarsSmall() {
        return this.http.get('/showcase/resources/data/cars-small.json')
                    .toPromise()
                    .then(res => <Car[]> res.json().data)
                    .then(data => { return data; });
    }

    getCarsMedium() {
        return [
            {"vin":"a1653d4d","brand":"Volkswagen","year":1998,"color":"White"},
            {"vin":"ddeb9b10","brand":"Mercedes","year":1985,"color":"Green"},
            {"vin":"d8ebe413","brand":"Jaguar","year":1979,"color":"Silver"},
            {"vin":"aab227b7","brand":"Audi","year":1970,"color":"Black"},
            {"vin":"631f7412","brand":"Volvo","year":1992,"color":"Red"},
            {"vin":"7d2d22b0","brand":"Volkswagen","year":1993,"color":"Maroon"},
            {"vin":"50e900ca","brand":"Fiat","year":1964,"color":"Blue"},
            {"vin":"4bbcd603","brand":"Renault","year":1983,"color":"Maroon"},
            {"vin":"70214c7e","brand":"Renault","year":1961,"color":"Black"},
            {"vin":"ec229a92","brand":"Audi","year":1984,"color":"Brown"},
            {"vin":"1083ee40","brand":"Volkswagen","year":1984,"color":"Silver"},
            {"vin":"6e0da3ab","brand":"Volvo","year":1987,"color":"Silver"},
            {"vin":"5aee636b","brand":"Jaguar","year":1995,"color":"Maroon"},
            {"vin":"7cc43997","brand":"Jaguar","year":1984,"color":"Orange"},
            {"vin":"88ec9f66","brand":"Honda","year":1989,"color":"Maroon"},
            {"vin":"f5a4a5f5","brand":"BMW","year":1986,"color":"Blue"},
            {"vin":"15b9a5c9","brand":"Mercedes","year":1986,"color":"Orange"},
            {"vin":"f7e18d01","brand":"Mercedes","year":1991,"color":"White"},
            {"vin":"cec593d7","brand":"Volkswagen","year":1992,"color":"Blue"},
            {"vin":"d5bac4f0","brand":"Renault","year":2001,"color":"Blue"},
            {"vin":"56b527c8","brand":"Jaguar","year":1990,"color":"Yellow"},
            {"vin":"1ac011ff","brand":"Audi","year":1966,"color":"Maroon"},
            {"vin":"fc074185","brand":"BMW","year":1962,"color":"Blue"},
            {"vin":"606ba663","brand":"Honda","year":1982,"color":"Blue"},
            {"vin":"d05060b8","brand":"Mercedes","year":2003,"color":"Silver"},
            {"vin":"46e4bbe8","brand":"Mercedes","year":1986,"color":"White"},
            {"vin":"c29da0d7","brand":"BMW","year":1983,"color":"Brown"},
            {"vin":"24622f70","brand":"Volkswagen","year":1973,"color":"Maroon"},
            {"vin":"7f573d2c","brand":"Mercedes","year":1991,"color":"Red"},
            {"vin":"b69e6f5c","brand":"Jaguar","year":1993,"color":"Yellow"},
            {"vin":"ead9bf1d","brand":"Fiat","year":1968,"color":"Maroon"},
            {"vin":"bc58113e","brand":"Renault","year":1981,"color":"Silver"},
            {"vin":"2989d5b1","brand":"Honda","year":2006,"color":"Blue"},
            {"vin":"c243e3a0","brand":"Fiat","year":1990,"color":"Maroon"},
            {"vin":"e3d3ebf3","brand":"Audi","year":1996,"color":"White"},
            {"vin":"45337e7a","brand":"Mercedes","year":1982,"color":"Blue"},
            {"vin":"36e9cf7e","brand":"Fiat","year":2000,"color":"Orange"},
            {"vin":"036bf135","brand":"Mercedes","year":1973,"color":"Black"},
            {"vin":"ad612e9f","brand":"Mercedes","year":1975,"color":"Red"},
            {"vin":"97c6e1e9","brand":"Volvo","year":1967,"color":"Green"},
            {"vin":"ae962274","brand":"Volvo","year":1982,"color":"Red"},
            {"vin":"81f8972a","brand":"BMW","year":2007,"color":"Black"},
            {"vin":"f8506743","brand":"Audi","year":1975,"color":"Blue"},
            {"vin":"596859d1","brand":"Fiat","year":2002,"color":"Green"},
            {"vin":"d83c1d9a","brand":"Volvo","year":1972,"color":"Black"},
            {"vin":"32f41550","brand":"Mercedes","year":1978,"color":"Brown"},
            {"vin":"c28cd2e4","brand":"Volvo","year":1982,"color":"Silver"},
            {"vin":"80890dcc","brand":"Audi","year":1962,"color":"White"},
            {"vin":"4bf1aeb5","brand":"Volkswagen","year":2000,"color":"Silver"},
            {"vin":"45ca4786","brand":"BMW","year":1995,"color":"Maroon"}
        ];
    }

    getCarsBig() {
        return [
            {
                "vin":"cd119843",
                "brand":"Fiat",
                "year":1996,
                "color":"White"
            },
            {
                "vin":"09cb93ea",
                "brand":"Jaguar",
                "year":2003,
                "color":"Maroon"
            },
            {
                "vin":"33a5d514",
                "brand":"Fiat",
                "year":2009,
                "color":"Black"
            },
            {
                "vin":"94becc53",
                "brand":"Volkswagen",
                "year":2000,
                "color":"White"
            },
            {
                "vin":"83d22e5e",
                "brand":"Jaguar",
                "year":1986,
                "color":"White"
            },
            {
                "vin":"03e9a521",
                "brand":"Audi",
                "year":2001,
                "color":"Black"
            },
            {
                "vin":"24afc4f6",
                "brand":"Fiat",
                "year":1974,
                "color":"Red"
            },
            {
                "vin":"8d5584dd",
                "brand":"BMW",
                "year":1989,
                "color":"Silver"
            },
            {
                "vin":"fe75a948",
                "brand":"Fiat",
                "year":1994,
                "color":"Maroon"
            },
            {
                "vin":"3afa6ae6",
                "brand":"Renault",
                "year":1966,
                "color":"Green"
            },
            {
                "vin":"195ca817",
                "brand":"Volkswagen",
                "year":1988,
                "color":"Yellow"
            },
            {
                "vin":"e079c5b1",
                "brand":"Volkswagen",
                "year":1994,
                "color":"Black"
            },
            {
                "vin":"2e0a0962",
                "brand":"Fiat",
                "year":1968,
                "color":"Orange"
            },
            {
                "vin":"9ae52842",
                "brand":"Mercedes",
                "year":1993,
                "color":"Brown"
            },
            {
                "vin":"1a2d051a",
                "brand":"Fiat",
                "year":1977,
                "color":"Silver"
            },
            {
                "vin":"ae3394ee",
                "brand":"Mercedes",
                "year":2004,
                "color":"Red"
            },
            {
                "vin":"c2e418e0",
                "brand":"Volvo",
                "year":2001,
                "color":"Yellow"
            },
            {
                "vin":"81d3c82b",
                "brand":"Renault",
                "year":1995,
                "color":"Blue"
            },
            {
                "vin":"bdade66a",
                "brand":"Jaguar",
                "year":1997,
                "color":"Maroon"
            },
            {
                "vin":"66769be1",
                "brand":"Volkswagen",
                "year":1986,
                "color":"Maroon"
            },
            {
                "vin":"e048781d",
                "brand":"Volvo",
                "year":1979,
                "color":"Silver"
            },
            {
                "vin":"7904ca6f",
                "brand":"Audi",
                "year":1975,
                "color":"Brown"
            },
            {
                "vin":"4fee7b06",
                "brand":"Jaguar",
                "year":2007,
                "color":"Maroon"
            },
            {
                "vin":"5bf33f2b",
                "brand":"BMW",
                "year":1995,
                "color":"Red"
            },
            {
                "vin":"dd4459b5",
                "brand":"Volkswagen",
                "year":1976,
                "color":"White"
            },
            {
                "vin":"657d5f25",
                "brand":"Volkswagen",
                "year":1976,
                "color":"Silver"
            },
            {
                "vin":"413c0897",
                "brand":"Fiat",
                "year":1976,
                "color":"Maroon"
            },
            {
                "vin":"6e055e7f",
                "brand":"Volvo",
                "year":1981,
                "color":"Brown"
            },
            {
                "vin":"a300aa0a",
                "brand":"BMW",
                "year":1963,
                "color":"Black"
            },
            {
                "vin":"29f4cea3",
                "brand":"Jaguar",
                "year":1985,
                "color":"Maroon"
            },
            {
                "vin":"99b9d8fe",
                "brand":"BMW",
                "year":2004,
                "color":"Red"
            },
            {
                "vin":"9f6e3633",
                "brand":"Fiat",
                "year":2003,
                "color":"Green"
            },
            {
                "vin":"548429f0",
                "brand":"Fiat",
                "year":1997,
                "color":"Red"
            },
            {
                "vin":"0ccd7bde",
                "brand":"Audi",
                "year":1993,
                "color":"White"
            },
            {
                "vin":"1f972f94",
                "brand":"Volvo",
                "year":1983,
                "color":"Blue"
            },
            {
                "vin":"2af3e9ed",
                "brand":"Renault",
                "year":1979,
                "color":"Yellow"
            },
            {
                "vin":"4066c9d6",
                "brand":"Mercedes",
                "year":1998,
                "color":"Black"
            },
            {
                "vin":"63e05aba",
                "brand":"Audi",
                "year":1988,
                "color":"Brown"
            },
            {
                "vin":"cab2b201",
                "brand":"Honda",
                "year":2000,
                "color":"Silver"
            },
            {
                "vin":"25b7a491",
                "brand":"Renault",
                "year":1966,
                "color":"Brown"
            },
            {
                "vin":"5b0a3794",
                "brand":"Audi",
                "year":1981,
                "color":"Yellow"
            },
            {
                "vin":"dfdc41bc",
                "brand":"Fiat",
                "year":2001,
                "color":"Yellow"
            },
            {
                "vin":"6c631dac",
                "brand":"Fiat",
                "year":1982,
                "color":"Red"
            },
            {
                "vin":"10e1f610",
                "brand":"Honda",
                "year":1993,
                "color":"Silver"
            },
            {
                "vin":"98e12787",
                "brand":"Mercedes",
                "year":2003,
                "color":"Yellow"
            },
            {
                "vin":"d943ae6b",
                "brand":"Fiat",
                "year":1993,
                "color":"Silver"
            },
            {
                "vin":"46d33845",
                "brand":"Renault",
                "year":1989,
                "color":"White"
            },
            {
                "vin":"249b7666",
                "brand":"BMW",
                "year":1970,
                "color":"Red"
            },
            {
                "vin":"0597f75e",
                "brand":"Fiat",
                "year":1998,
                "color":"Black"
            },
            {
                "vin":"97e8494f",
                "brand":"Fiat",
                "year":2003,
                "color":"Blue"
            }
        ];
    }
}