import { Routes } from '@angular/router';
import { LandingComponent } from '@pages/landing/landing.component';
import { AppMainComponent } from './app.main.component';

export const routes: Routes = [
    { path: '', component: LandingComponent, pathMatch: 'full' },
    {
        path: '',
        component: AppMainComponent,
        children: [
            { path: '', redirectTo: 'installation', pathMatch: 'full' },
            { path: 'accessibility', redirectTo: 'guides/accessibility', pathMatch: 'full' },
            { path: 'autocomplete', loadChildren: () => import('@pages/autocomplete/routes') },
            { path: 'installation', loadChildren: () => import('@pages/installation/installation.module').then((m) => m.InstallationModule) },
            { path: 'configuration', loadChildren: () => import('@pages/configuration/configurationdemo.module').then((m) => m.ConfigurationDemoModule) },
            { path: 'playground', loadChildren: () => import('@pages/playground/playground.module').then((m) => m.PlaygroundModule) },
            { path: 'roadmap', loadChildren: () => import('@pages/roadmap/roadmap.module').then((m) => m.RoadmapModule) },
            { path: 'team', loadChildren: () => import('@pages/team/team.module').then((m) => m.TeamModule) },
            { path: 'partners', loadChildren: () => import('@pages/partners/partners.module').then((m) => m.PartnersModule) },
            { path: 'theming', loadChildren: () => import('@pages/theming/theming.module').then((m) => m.ThemingModule) },
            { path: 'icons', loadChildren: () => import('@pages/icons/iconsdemo.module').then((m) => m.IconsDemoModule) },
            { path: 'customicons', loadChildren: () => import('@pages/customicons/customiconsdemo.module').then((m) => m.CustomIconsDemoModule) },
            { path: 'accordion', loadChildren: () => import('@pages/accordion/accordiondemo.module').then((m) => m.AccordionDemoModule) },
            { path: 'avatar', loadChildren: () => import('@pages/avatar/avatardemo.module').then((m) => m.AvatarDemoModule) },
            { path: 'blockui', loadChildren: () => import('@pages/blockui/blockuidemo.module').then((m) => m.BlockUIDemoModule) },
            { path: 'badge', loadChildren: () => import('@pages/badge/badgedemo.module').then((m) => m.BadgeDemoModule) },
            { path: 'breadcrumb', loadChildren: () => import('@pages/breadcrumb/breadcrumbdemo.module').then((m) => m.BreadcrumbDemoModule) },
            { path: 'button', loadChildren: () => import('@pages/button/buttondemo.module').then((m) => m.ButtonDemoModule) },
            { path: 'datepicker', loadChildren: () => import('@pages/datepicker/datepickerdemo.module').then((m) => m.DatePickerDemoModule) },
            { path: 'card', loadChildren: () => import('@pages/card/carddemo.module').then((m) => m.CardDemoModule) },
            { path: 'cascadeselect', loadChildren: () => import('@pages/cascadeselect/cascadeselectdemo.module').then((m) => m.CascadeSelectDemoModule) },
            { path: 'carousel', loadChildren: () => import('@pages/carousel/carouseldemo.module').then((m) => m.CarouselDemoModule) },
            { path: 'chart', loadChildren: () => import('@pages/chart/chartdemo.module').then((m) => m.ChartDemoModule) },
            { path: 'checkbox', loadChildren: () => import('@pages/checkbox/checkboxdemo.module').then((m) => m.CheckboxDemoModule) },
            { path: 'chip', loadChildren: () => import('@pages/chip/chipdemo.module').then((m) => m.ChipDemoModule) },
            { path: 'chips', loadChildren: () => import('@pages/chips/chipsdemo.module').then((m) => m.ChipsDemoModule) },
            { path: 'colorpicker', loadChildren: () => import('@pages/colorpicker/colorpickerdemo.module').then((m) => m.ColorPickerDemoModule) },
            { path: 'colors', loadChildren: () => import('@pages/colors/colorsdemo.module').then((m) => m.ColorsDemoModule) },
            { path: 'confirmdialog', loadChildren: () => import('@pages/confirmdialog/confirmdialogdemo.module').then((m) => m.ConfirmDialogDemoModule) },
            { path: 'confirmpopup', loadChildren: () => import('@pages/confirmpopup/confirmpopupdemo.module').then((m) => m.ConfirmPopupDemoModule) },
            { path: 'contextmenu', loadChildren: () => import('@pages/contextmenu/contextmenudemo.module').then((m) => m.ContextMenuDemoModule) },
            { path: 'dataview', loadChildren: () => import('@pages/dataview/dataviewdemo.module').then((m) => m.DataViewDemoModule) },
            { path: 'defer', loadChildren: () => import('@pages/defer/deferdemo.module').then((m) => m.DeferDemoModule) },
            { path: 'dialog', loadChildren: () => import('@pages/dialog/dialogdemo.module').then((m) => m.DialogDemoModule) },
            { path: 'dock', loadChildren: () => import('@pages/dock/dockdemo.module').then((m) => m.DockDemoModule) },
            { path: 'divider', loadChildren: () => import('@pages/divider/dividerdemo.module').then((m) => m.DividerDemoModule) },
            { path: 'dynamicdialog', loadChildren: () => import('@pages/dynamicdialog/dynamicdialogdemo.module').then((m) => m.DynamicDialogDemoModule) },
            { path: 'dragdrop', loadChildren: () => import('@pages/dragdrop/dragdropdemo.module').then((m) => m.DragDropDemoModule) },
            { path: 'select', loadChildren: () => import('@pages/select/selectdemo.module').then((m) => m.SelectDemoModule) },
            { path: 'iconfield', loadChildren: () => import('@pages/iconfield/iconfielddemo.module').then((m) => m.IconFieldDemoModule) },
            { path: 'editor', loadChildren: () => import('@pages/editor/editordemo.module').then((m) => m.EditorDemoModule) },
            { path: 'floatlabel', loadChildren: () => import('@pages/floatlabel/floatlabeldemo.module').then((m) => m.FloatLabelDemoModule) },
            { path: 'fieldset', loadChildren: () => import('@pages/fieldset/fieldsetdemo.module').then((m) => m.FieldsetDemoModule) },
            { path: 'fileupload', loadChildren: () => import('@pages/fileupload/fileuploaddemo.module').then((m) => m.FileUploadDemoModule) },
            { path: 'filterservice', loadChildren: () => import('@pages/filterservice/filterservicedemo.module').then((m) => m.FilterServiceDemoModule) },
            { path: 'focustrap', loadChildren: () => import('@pages/focustrap/focustrapdemo.module').then((m) => m.FocusTrapDemoModule) },
            { path: 'galleria', loadChildren: () => import('@pages/galleria/galleriademo.module').then((m) => m.GalleriaDemoModule) },
            { path: 'image', loadChildren: () => import('@pages/image/imagedemo.module').then((m) => m.ImageDemoModule) },
            { path: 'inplace', loadChildren: () => import('@pages/inplace/inplacedemo.module').then((m) => m.InplaceDemoModule) },
            { path: 'fluid', loadChildren: () => import('@pages/fluid/fluiddemo.module').then((m) => m.FluidDemoModule) },
            { path: 'metergroup', loadChildren: () => import('@pages/metergroup/metergroupdemo.module').then((m) => m.MeterGroupDemoModule) },
            { path: 'inputmask', loadChildren: () => import('@pages/inputmask/inputmaskdemo.module').then((m) => m.InputMaskDemoModule) },
            { path: 'inputnumber', loadChildren: () => import('@pages/inputnumber/inputnumberdemo.module').then((m) => m.InputNumberDemoModule) },
            { path: 'inputotp', loadChildren: () => import('@pages/inputotp/inputotpdemo.module').then((m) => m.InputOtpDemoModule) },
            { path: 'toggleswitch', loadChildren: () => import('@pages/toggleswitch/toggleswitchdemo.module').then((m) => m.ToggleSwitchDemoModule) },
            { path: 'inputtext', loadChildren: () => import('@pages/inputtext/inputtextdemo.module').then((m) => m.InputTextDemoModule) },
            { path: 'inputgroup', loadChildren: () => import('@pages/inputgroup/inputgroupdemo.module').then((m) => m.InputGroupDemoModule) },
            { path: 'inputtextarea', loadChildren: () => import('@pages/inputtextarea/inputtextareademo.module').then((m) => m.InputTextareaDemoModule) },
            { path: 'knob', loadChildren: () => import('@pages/knob/knobdemo.module').then((m) => m.KnobDemoModule) },
            { path: 'keyfilter', loadChildren: () => import('@pages/keyfilter/keyfilterdemo.module').then((m) => m.KeyFilterDemoModule) },
            { path: 'listbox', loadChildren: () => import('@pages/listbox/listboxdemo.module').then((m) => m.ListboxDemoModule) },
            { path: 'lts', loadChildren: () => import('@pages/lts/lts.module').then((m) => m.LTSModule) },
            { path: 'megamenu', loadChildren: () => import('@pages/megamenu/megamenudemo.module').then((m) => m.MegaMenuDemoModule) },
            { path: 'menu', loadChildren: () => import('@pages/menu/menudemo.module').then((m) => m.MenuDemoModule) },
            { path: 'menubar', loadChildren: () => import('@pages/menubar/menubardemo.module').then((m) => m.MenubarDemoModule) },
            { path: 'messages', loadChildren: () => import('@pages/messages/messagesdemo.module').then((m) => m.MessagesDemoModule) },
            { path: 'multiselect', loadChildren: () => import('@pages/multiselect/multiselectdemo.module').then((m) => m.MultiSelectDemoModule) },
            { path: 'orderlist', loadChildren: () => import('@pages/orderlist/orderlistdemo.module').then((m) => m.OrderListDemoModule) },
            { path: 'organizationchart', loadChildren: () => import('@pages/organizationchart/organizationchartdemo.module').then((m) => m.OrganizationChartDemoModule) },
            { path: 'popover', loadChildren: () => import('@pages/popover/popoverdemo.module').then((m) => m.PopoverDemoModule) },
            { path: 'paginator', loadChildren: () => import('@pages/paginator/paginatordemo.module').then((m) => m.PaginatorDemoModule) },
            { path: 'panel', loadChildren: () => import('@pages/panel/paneldemo.module').then((m) => m.PanelDemoModule) },
            { path: 'panelmenu', loadChildren: () => import('@pages/panelmenu/panelmenudemo.module').then((m) => m.PanelMenuDemoModule) },
            { path: 'password', loadChildren: () => import('@pages/password/passworddemo.module').then((m) => m.PasswordDemoModule) },
            { path: 'picklist', loadChildren: () => import('@pages/picklist/picklistdemo.module').then((m) => m.PickListDemoModule) },
            { path: 'progressbar', loadChildren: () => import('@pages/progressbar/progressbardemo.module').then((m) => m.ProgressBarDemoModule) },
            { path: 'progressspinner', loadChildren: () => import('@pages/progressspinner/progressspinnerdemo.module').then((m) => m.ProgressSpinnerDemoModule) },
            { path: 'radiobutton', loadChildren: () => import('@pages/radiobutton/radiobuttondemo.module').then((m) => m.RadioButtonDemoModule) },
            { path: 'rating', loadChildren: () => import('@pages/rating/ratingdemo.module').then((m) => m.RatingDemoModule) },
            { path: 'ripple', loadChildren: () => import('@pages/ripple/rippledemo.module').then((m) => m.RippleDemoModule) },
            { path: 'scrollpanel', loadChildren: () => import('@pages/scrollpanel/scrollpaneldemo.module').then((m) => m.ScrollPanelDemoModule) },
            { path: 'scrolltop', loadChildren: () => import('@pages/scrolltop/scrolltopdemo.module').then((m) => m.ScrollTopDemoModule) },
            { path: 'selectbutton', loadChildren: () => import('@pages/selectbutton/selectbuttondemo.module').then((m) => m.SelectButtonDemoModule) },
            { path: 'sidebar', loadChildren: () => import('@pages/sidebar/sidebardemo.module').then((m) => m.SidebarDemoModule) },
            { path: 'skeleton', loadChildren: () => import('@pages/skeleton/skeletondemo.module').then((m) => m.SkeletonDemoModule) },
            { path: 'slider', loadChildren: () => import('@pages/slider/sliderdemo.module').then((m) => m.SliderDemoModule) },
            { path: 'speeddial', loadChildren: () => import('@pages/speeddial/speeddialdemo.module').then((m) => m.SpeedDialDemoModule) },
            { path: 'splitbutton', loadChildren: () => import('@pages/splitbutton/splitbuttondemo.module').then((m) => m.SplitButtonDemoModule) },
            { path: 'splitter', loadChildren: () => import('@pages/splitter/splitterdemo.module').then((m) => m.SplitterDemoModule) },
            { path: 'stepper', loadChildren: () => import('@pages/stepper/stepperdemo.module').then((m) => m.StepperDemoModule) },
            { path: 'steps', loadChildren: () => import('@pages/steps/stepsdemo.module').then((m) => m.StepsDemoModule) },
            { path: 'support', loadChildren: () => import('@pages/support/support.module').then((m) => m.SupportModule) },
            { path: 'styleclass', loadChildren: () => import('@pages/styleclass/styleclassdemo.module').then((m) => m.StyleClassDemoModule) },
            { path: 'tag', loadChildren: () => import('@pages/tag/tagdemo.module').then((m) => m.TagDemoModule) },
            { path: 'table', loadChildren: () => import('@pages/table/tabledemo.module').then((m) => m.TableDemoModule) },
            { path: 'tabmenu', loadChildren: () => import('@pages/tabmenu/tabmenudemo.module').then((m) => m.TabMenuDemoModule) },
            { path: 'tabview', loadChildren: () => import('@pages/tabview/tabviewdemo.module').then((m) => m.TabViewDemoModule) },
            { path: 'terminal', loadChildren: () => import('@pages/terminal/terminaldemo.module').then((m) => m.TerminalDemoModule) },
            { path: 'tieredmenu', loadChildren: () => import('@pages/tieredmenu/tieredmenudemo.module').then((m) => m.TieredMenuDemoModule) },
            { path: 'timeline', loadChildren: () => import('@pages/timeline/timelinedemo.module').then((m) => m.TimelineDemoModule) },
            { path: 'toast', loadChildren: () => import('@pages/toast/toastdemo.module').then((m) => m.ToastDemoModule) },
            { path: 'togglebutton', loadChildren: () => import('@pages/togglebutton/togglebuttondemo.module').then((m) => m.ToggleButtonDemoModule) },
            { path: 'toolbar', loadChildren: () => import('@pages/toolbar/toolbardemo.module').then((m) => m.ToolbarDemoModule) },
            { path: 'tooltip', loadChildren: () => import('@pages/tooltip/tooltipdemo.module').then((m) => m.TooltipDemoModule) },
            { path: 'tree', loadChildren: () => import('@pages/tree/treedemo.module').then((m) => m.TreeDemoModule) },
            { path: 'treeselect', loadChildren: () => import('@pages/treeselect/treeselectdemo.module').then((m) => m.TreeSelectDemoModule) },
            { path: 'treetable', loadChildren: () => import('@pages/treetable/treetabledemo.module').then((m) => m.TreeTableDemoModule) },
            { path: 'tristatecheckbox', loadChildren: () => import('@pages/tristatecheckbox/tristatecheckboxdemo.module').then((m) => m.TriStateCheckboxDemoModule) },
            { path: 'scroller', loadChildren: () => import('@pages/scroller/scrollerdemo.module').then((m) => m.ScrollerDemoModule) },
            { path: 'uikit', loadChildren: () => import('@pages/uikit/uikit.module').then((m) => m.UIKitModule) },
            { path: 'autofocus', loadChildren: () => import('@pages/autofocus/autofocusdemo.module').then((m) => m.AutoFocusDemoModule) },
            { path: 'overlay', loadChildren: () => import('@pages/overlay/overlaydemo.module').then((m) => m.OverlayDemoModule) },
            { path: 'animateonscroll', loadChildren: () => import('@pages/animate/animateonscrolldemo.module').then((m) => m.AnimateOnScrollDemoModule) },
            { path: 'templates', loadChildren: () => import('@pages/templates/templates.module').then((m) => m.TemplatesModule) },
            { path: 'guides', loadChildren: () => import('@pages/guides/guides.module').then((m) => m.GuidesModule) }
        ]
    },
    { path: 'notfound', loadChildren: () => import('@pages/notfound/notfound.module').then((m) => m.NotFoundModule) },
    { path: '**', redirectTo: '/notfound' }
];
