#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Warning: This will discard all uncommitted changes and remove untracked files."
echo "Proceed? (y/n)"
read -r response
if [ "$response" != "y" ]; then
  echo "Operation canceled."
  exit 0
fi

git reset --hard HEAD && git clean -fd

npm run setup
