name: Comment By Label In Issues and PRs

on:
  issues:
    types: [labeled]

permissions:
  contents: read

jobs:
  add-comment:
    if: contains(github.event.label.name, 'Help Wanted')
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@c9fcb64660bc90ec1cc535646af190c992007c32
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This issue is available for anyone to work on. **Make sure to reference this issue in your pull request.** :sparkles: Thank you for your contribution! :sparkles:
